use_frameworks!

platform :ios, '10.0'

target 'TencentCloudCustomer_Example' do
  pod 'TencentCloudCustomer', :path => '../'

  target 'TencentCloudCustomer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
